# GeckoTerminal Data Collector Configuration
# This file contains all configurable settings for the data collection system

# DEX Configuration
dexes:
  targets:
    - heaven
    - pumpswap
  network: solana

# Collection Intervals
intervals:
  #top_pools_monitoring: "1h"    # How often to check top pools
  top_pools_monitoring: "5m"    # How often to check top pools
  ohlcv_collection: "1h"        # OHLCV data collection frequency
  trade_collection: "30m"       # Trade data collection frequency
  watchlist_check: "1h"         # Watchlist file check frequency

# Thresholds and Limits
thresholds:
  min_trade_volume_usd: 100     # Minimum trade volume to collect (USD)
  max_retries: 3                # Maximum retry attempts for failed operations
  rate_limit_delay: 1.0         # Delay between API requests (seconds)
  backoff_factor: 2.0           # Exponential backoff multiplier

# OHLCV Timeframe Configuration
timeframes:
  ohlcv_default: "1h"           # Default timeframe for OHLCV collection
  supported:                    # All supported timeframes
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "12h"
    - "1d"

# Database Configuration
database:
  url: "postgresql://gecko_collector:12345678!@localhost:5432/gecko_terminal_collector"  # Database connection URL
  pool_size: 10                   # Connection pool size
  echo: false                     # Enable SQL query logging
  timeout: 30                     # Connection timeout (seconds)

# API Configuration
api:
  base_url: "https://api.geckoterminal.com/api/v2"
  timeout: 30                     # Request timeout (seconds)
  max_concurrent: 5               # Maximum concurrent API requests
  rate_limit_delay: 1.0           # Rate limiting delay (seconds)

# Error Handling Configuration
error_handling:
  max_retries: 3                  # Maximum retry attempts
  backoff_factor: 2.0             # Exponential backoff factor
  circuit_breaker_threshold: 5    # Failures before circuit breaker opens
  circuit_breaker_timeout: 300    # Circuit breaker timeout (seconds)

# Rate Limiting Configuration
rate_limiting:
  requests_per_minute: 30         # Global requests per minute limit
  daily_limit: 10000              # Global daily request limit
  circuit_breaker_threshold: 5    # Failures before circuit breaker opens
  circuit_breaker_timeout: 300    # Circuit breaker timeout (seconds)
  backoff_base_delay: 1.0         # Base delay for exponential backoff
  backoff_max_delay: 300.0        # Maximum backoff delay
  backoff_jitter_factor: 0.3      # Jitter factor for backoff
  state_file_dir: ".rate_limiter_state"  # Directory for rate limiter state files

# Watchlist Configuration
watchlist:
  file_path: "watchlist.csv"      # Path to watchlist CSV file
  check_interval: "1h"            # How often to check for file changes
  auto_add_new_tokens: true       # Automatically add new tokens from watchlist
  remove_inactive_tokens: false   # Remove tokens no longer in watchlist

# NautilusTrader POC Configuration
nautilus_poc:
  # Environment settings - can be overridden via NAUTILUS_ENVIRONMENT
  environment: "testnet"          # "testnet" or "mainnet"
  
  # Multi-environment configurations
  environments:
    testnet:
      solana:
        network: "testnet"
        rpc_endpoint: "https://api.testnet.solana.com"
        commitment: "confirmed"
        cluster: "testnet"
      pumpswap:
        max_slippage_percent: 10.0    # Higher slippage tolerance for testnet
        base_position_size: 0.01      # Smaller positions for testing
        max_position_size: 0.1        # Conservative max for testnet
        min_liquidity_sol: 1.0        # Lower liquidity requirement for testnet
        max_price_impact_percent: 15.0 # Higher impact tolerance for testing
        realistic_transaction_cost: 0.001  # 10 bps for testnet
      security:
        validate_token_addresses: true
        require_transaction_confirmation: true
        enable_circuit_breaker: true
        max_daily_trades: 100
        wallet_balance_alert_threshold: 0.1  # Alert when below 0.1 SOL
      
    mainnet:
      solana:
        network: "mainnet"
        rpc_endpoint: "https://api.mainnet-beta.solana.com"
        commitment: "finalized"
        cluster: "mainnet-beta"
      pumpswap:
        max_slippage_percent: 5.0     # Stricter slippage for mainnet
        base_position_size: 0.1       # Standard position size
        max_position_size: 0.5        # Higher max for mainnet
        min_liquidity_sol: 10.0       # Higher liquidity requirement
        max_price_impact_percent: 10.0 # Stricter impact tolerance
        realistic_transaction_cost: 0.0005  # 5 bps for mainnet
      security:
        validate_token_addresses: true
        require_transaction_confirmation: true
        enable_circuit_breaker: true
        max_daily_trades: 500
        wallet_balance_alert_threshold: 1.0  # Alert when below 1.0 SOL
  
  # Q50 Signal Configuration
  q50:
    features_path: "data3/macro_features.pkl"  # Path to Q50 signals file
    signal_tolerance_minutes: 5     # Tolerance for timestamp matching
    required_columns:               # Required Q50 columns for validation
      - "q10"
      - "q50" 
      - "q90"
      - "vol_raw"
      - "vol_risk"
      - "prob_up"
      - "economically_significant"
      - "high_quality"
      - "tradeable"
    backup_features_path: ""        # Optional backup path for signals
    signal_cache_ttl_minutes: 60    # Cache TTL for loaded signals
  
  # Wallet and Security Configuration (set via environment variables)
  wallet:
    # These should NEVER be set in config file - use environment variables only
    payer_public_key: ""           # Set via NAUTILUS_PAYER_PUBLIC_KEY
    private_key_path: ""           # Set via NAUTILUS_PRIVATE_KEY_PATH
    private_key_env_var: ""        # Set via NAUTILUS_PRIVATE_KEY_ENV_VAR
    wallet_password_env_var: ""    # Set via NAUTILUS_WALLET_PASSWORD_ENV_VAR
    
    # Wallet validation settings
    validate_balance_before_trade: true
    min_balance_sol: 0.1           # Minimum balance to maintain
    balance_check_interval_minutes: 5
    
  # Trading Parameters (environment-specific overrides applied)
  trading:
    # Position sizing
    kelly_multiplier: 1.0          # Kelly criterion multiplier
    max_portfolio_risk: 0.2        # Maximum portfolio risk (20%)
    position_concentration_limit: 0.1  # Max 10% in single position
    
    # Execution parameters
    order_timeout_seconds: 30      # Order execution timeout
    confirmation_timeout_seconds: 60  # Transaction confirmation timeout
    max_gas_price_lamports: 5000   # Maximum gas price willing to pay
    
    # Risk management
    stop_loss_percent: 20.0        # Automatic stop loss threshold
    take_profit_percent: 50.0      # Take profit threshold
    position_timeout_hours: 24     # Maximum holding period
    max_consecutive_losses: 5      # Circuit breaker trigger
    
  # NautilusTrader Configuration
  nautilus:
    instance_id: "NAUTILUS-001"    # Unique instance identifier
    log_level: "INFO"              # Logging level
    cache_database_path: "cache.db" # Cache database path
    
    # Strategy configuration
    strategy_config:
      risk_engine_config:
        bypass: false              # Enable risk engine
        max_order_rate: "100/00:00:01"  # Max orders per second
        max_notional_per_order: 1000000  # Max notional per order
      
      exec_engine_config:
        reconciliation: true       # Enable position reconciliation
        inflight_check_interval_ms: 5000  # Check interval for inflight orders
        
    # Data engine configuration
    data_engine_config:
      time_bars_build_with_no_updates: false
      time_bars_timestamp_on_close: true
      validate_data_sequence: true
    
  # Performance Monitoring
  monitoring:
    enable_performance_tracking: true
    log_signal_processing: true
    log_trade_execution: true
    log_pumpswap_interactions: true
    log_wallet_operations: true
    log_security_events: true
    
    # Metrics collection
    collect_execution_metrics: true
    collect_pnl_metrics: true
    collect_slippage_metrics: true
    metrics_export_interval_minutes: 15
    
    # Performance thresholds
    signal_processing_timeout_ms: 1000
    trade_execution_timeout_ms: 30000
    max_acceptable_slippage_percent: 5.0
    
  # Error Handling and Recovery
  error_handling:
    max_retries: 3
    retry_delay_base: 1.0
    retry_delay_max: 60.0
    circuit_breaker_threshold: 5
    circuit_breaker_timeout: 300
    
    # Specific error handling
    rpc_error_retry_count: 5
    rpc_error_backoff_factor: 2.0
    pumpswap_error_retry_count: 3
    wallet_error_retry_count: 2
    
    # Recovery strategies
    enable_graceful_degradation: true
    fallback_to_hold_on_error: true
    auto_restart_on_critical_error: false
    
  # Security Configuration
  security:
    # Token validation
    validate_token_addresses: true
    token_blacklist_path: "security/token_blacklist.json"
    token_whitelist_path: "security/token_whitelist.json"
    enable_token_metadata_validation: true
    
    # Transaction security
    require_transaction_confirmation: true
    max_transaction_retries: 3
    transaction_signature_validation: true
    
    # Operational security
    enable_audit_logging: true
    audit_log_path: "logs/security_audit.log"
    sensitive_data_masking: true
    
    # Rate limiting for security
    max_trades_per_minute: 10
    max_trades_per_hour: 100
    max_trades_per_day: 500
    
  # Regime Detection
  regime_detection:
    vol_risk_percentiles:
      low: 0.30
      high: 0.70
      extreme: 0.90
    regime_multipliers:
      low_variance: 0.7
      medium_variance: 1.0
      high_variance: 1.4
      extreme_variance: 1.8
    
    # Adaptive thresholds
    enable_adaptive_thresholds: true
    threshold_adjustment_factor: 0.1
    min_threshold_adjustment: -0.5
    max_threshold_adjustment: 1.0

# New Pools Collection Configuration
new_pools:
  networks:
    solana:
      enabled: true               # Enable new pools collection for Solana
      interval: "10m"             # Collection interval for Solana (increased frequency)
      rate_limit_key: "new_pools_solana"  # Rate limiter key for Solana
      signal_analysis: true       # Enable signal analysis for collected pools
      auto_watchlist_integration: true  # Auto-add high-signal pools to watchlist
    #ethereum:
    #  enabled: false              # Enable new pools collection for Ethereum
    #  interval: "15m"             # Collection interval for Ethereum
    #  rate_limit_key: "new_pools_ethereum"  # Rate limiter key for Ethereum
    #  signal_analysis: true       # Enable signal analysis for collected pools
    #  auto_watchlist_integration: true  # Auto-add high-signal pools to watchlist
  
  # Signal Detection Configuration
  signal_detection:
    enabled: true                 # Enable signal detection system
    min_signal_score: 60.0        # Minimum signal score for alerts
    volume_spike_threshold: 2.0   # Volume spike detection (2x increase)
    liquidity_growth_threshold: 1.5  # Liquidity growth threshold (1.5x increase)
    momentum_lookback_hours: 6    # Hours to look back for momentum calculation
    auto_watchlist_threshold: 75.0  # Signal score threshold for auto-watchlist addition

# Environment Variable Overrides:
# You can override any configuration value using environment variables:
#
# Database:
#   GECKO_DB_URL - Database connection URL
#   GECKO_DB_POOL_SIZE - Connection pool size
#   GECKO_DB_ECHO - Enable SQL logging (true/false)
#   GECKO_DB_TIMEOUT - Connection timeout
#
# API:
#   GECKO_API_BASE_URL - API base URL
#   GECKO_API_TIMEOUT - Request timeout
#   GECKO_API_MAX_CONCURRENT - Max concurrent requests
#   GECKO_API_RATE_LIMIT_DELAY - Rate limit delay
#
# DEX:
#   GECKO_DEX_TARGETS - Comma-separated list of DEX targets
#   GECKO_DEX_NETWORK - Blockchain network
#
# Thresholds:
#   GECKO_MIN_TRADE_VOLUME - Minimum trade volume
#   GECKO_MAX_RETRIES - Maximum retries
#   GECKO_RATE_LIMIT_DELAY - Rate limit delay
#   GECKO_BACKOFF_FACTOR - Backoff factor
#
# Intervals:
#   GECKO_TOP_POOLS_INTERVAL - Top pools monitoring interval
#   GECKO_OHLCV_INTERVAL - OHLCV collection interval
#   GECKO_TRADE_INTERVAL - Trade collection interval
#   GECKO_WATCHLIST_INTERVAL - Watchlist check interval
#
# Timeframes:
#   GECKO_OHLCV_DEFAULT_TIMEFRAME - Default OHLCV timeframe
#
# Error Handling:
#   GECKO_ERROR_MAX_RETRIES - Error handling max retries
#   GECKO_ERROR_BACKOFF_FACTOR - Error handling backoff factor
#   GECKO_ERROR_CIRCUIT_BREAKER_THRESHOLD - Circuit breaker threshold
#   GECKO_ERROR_CIRCUIT_BREAKER_TIMEOUT - Circuit breaker timeout
#
# Watchlist:
#   GECKO_WATCHLIST_FILE_PATH - Watchlist file path
#   GECKO_WATCHLIST_CHECK_INTERVAL - Watchlist check interval
#   GECKO_WATCHLIST_AUTO_ADD - Auto add new tokens (true/false)
#   GECKO_WATCHLIST_REMOVE_INACTIVE - Remove inactive tokens (true/false)